version: '3.3'

services:
    fibonacci-api:
        build: .
        ports:
            - 8000:8000
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    redis:
        image: redis:6.0.6-alpine
        command: redis-server
